name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 'feat/*'
  pull_request:
    branches:
      - main
      - 'feat/*'
  workflow_dispatch:
    inputs:
      major_version_bump:
        description: 'Bump the major version'
        required: false
        default: 'false'

jobs:
  # Test job that runs on both main and feat/* branches
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  # Build and publish job that only runs on the main branch
  build-and-publish:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Set npm registry and authenticate
        run: |
          npm set registry https://registry.npmjs.org/
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Set Git user identity
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Build Documentation
        run: npm run docs

      - name: Bump version and push changes
        run: |
          if [ "${{ github.event.inputs.major_version_bump }}" == "true" ]; then
            npm version major -m "chore: bump major version to %s"
          else
            npm version patch -m "chore: bump patch version to %s"
          fi
          # Push the commit and tags in a single push command
          git push origin HEAD:main --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
